
OBJECTS = 
CFLAGS = -std=c99 -Wall -no-pie  
LDLIBS = 
CC=gcc


all: password_check 


password_check: password_check.c
	$(CC) $(CFLAGS) $(LDLIBS) -o password_check password_check.c 

clean:
	rm password_check

