
OBJECTS = 
CFLAGS = -std=c99 -Wall  
LDLIBS = 
CC=gcc


all: password_encryption 


password_encryption: password_encryption.c
	$(CC) $(CFLAGS) $(LDLIBS) -o password_encryption password_encryption.c 

clean:
	rm password_encryption

